server:
  port: 8764
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
ribbon:
  eureka:
    enabled: true
    
spring:
   freemarker:
    suffix: .ftl 
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
   resources:
      static-locations:["/templates/","/static/"]

   application:
    name: mobile
    