server:
  port: 8763
  context-path: /nessage
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: nessage
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: lizhangpengjava@163.com
    password: bingheart0
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true